create table "public"."schedule" (
    "id" bigint generated by default as identity not null,
    "start_date" date not null,
    "start_time" time without time zone not null,
    "referee" character varying not null,
    "status" character varying not null default 'before'::character varying
);


alter table "public"."schedule" enable row level security;

create table "public"."team" (
    "id" bigint generated by default as identity not null,
    "name" character varying not null,
    "players" json not null,
    "reserve_players" json not null,
    "type" character varying not null
);


alter table "public"."team" enable row level security;

create table "public"."team_schedule" (
    "id" bigint generated by default as identity not null,
    "team_id" bigint,
    "schedule_id" bigint,
    "type" character varying not null default 'before'::character varying,
    "score" json
);


alter table "public"."team_schedule" enable row level security;

CREATE UNIQUE INDEX schedule_pkey ON public.schedule USING btree (id);

CREATE UNIQUE INDEX team_pkey ON public.team USING btree (id);

CREATE UNIQUE INDEX team_schedule_pkey ON public.team_schedule USING btree (id);

alter table "public"."schedule" add constraint "schedule_pkey" PRIMARY KEY using index "schedule_pkey";

alter table "public"."team" add constraint "team_pkey" PRIMARY KEY using index "team_pkey";

alter table "public"."team_schedule" add constraint "team_schedule_pkey" PRIMARY KEY using index "team_schedule_pkey";

alter table "public"."team_schedule" add constraint "team_schedule_schedule_id_fkey" FOREIGN KEY (schedule_id) REFERENCES schedule(id) not valid;

alter table "public"."team_schedule" validate constraint "team_schedule_schedule_id_fkey";

alter table "public"."team_schedule" add constraint "team_schedule_team_id_fkey" FOREIGN KEY (team_id) REFERENCES team(id) not valid;

alter table "public"."team_schedule" validate constraint "team_schedule_team_id_fkey";

create policy "Enable read access for all users"
on "public"."schedule"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."team"
as permissive
for select
to public
using (true);


create policy "Enable read access for all users"
on "public"."team_schedule"
as permissive
for select
to public
using (true);



