create table "public"."predection" (
    "id" bigint generated by default as identity not null,
    "choices" json not null,
    "result" bigint,
    "schedule_id" bigint not null
);


alter table "public"."predection" enable row level security;

create table "public"."user_predection" (
    "id" bigint generated by default as identity not null,
    "user_id" uuid not null,
    "predection_id" bigint not null,
    "choice" bigint not null,
    "created_at" timestamp with time zone not null default now()
);


alter table "public"."user_predection" enable row level security;

CREATE UNIQUE INDEX predection_pkey ON public.predection USING btree (id);

CREATE UNIQUE INDEX user_predection_pkey ON public.user_predection USING btree (id);

alter table "public"."predection" add constraint "predection_pkey" PRIMARY KEY using index "predection_pkey";

alter table "public"."user_predection" add constraint "user_predection_pkey" PRIMARY KEY using index "user_predection_pkey";

alter table "public"."predection" add constraint "predection_schedule_id_fkey" FOREIGN KEY (schedule_id) REFERENCES schedule(id) not valid;

alter table "public"."predection" validate constraint "predection_schedule_id_fkey";

alter table "public"."user_predection" add constraint "user_predection_predection_id_fkey" FOREIGN KEY (predection_id) REFERENCES predection(id) not valid;

alter table "public"."user_predection" validate constraint "user_predection_predection_id_fkey";

alter table "public"."user_predection" add constraint "user_predection_user_id_fkey" FOREIGN KEY (user_id) REFERENCES "user"(id) not valid;

alter table "public"."user_predection" validate constraint "user_predection_user_id_fkey";


